.TH watchgate 1
.SH NAME
watchgate
.SH SYNOPSIS
.B watchgate $USER
.SH DESCRIPTION
Time based One Time Password - TOTP written as Bash/SHELL Cron service.
.SH MAINTENANCE FUNCTIONS
These "current Bash session" functions are only required for maintenance, and are not needed for daily use of Cron service.
.TP
.I "${Watchgate[@]}"
An associative array contains absolute path to executable commands will be exported into current SHELL session.
.TP
.I "watchgate.seed"
Generate a secret "seed" file using sha512sum from /dev/random, encrypt/sign it with OpenPGP DES 128.
.TP
.I "watchgate.seed.install/uninstall"
Install/Uninstall both the secret seed and encrypted seed.asc into /etc/watchgate/. The secret seed will only be visible for root user (User=root in systemd timer service).
.SH SCRIPTS
.TP
.I "$prefix/watchgate.cron"
Generate a TOTP, based on the secret seed, current time stamp and user account name. Also replaces a set of chosen accounts (users whose SHELL isn't nologin) password with these new generated one.
.TP
.I "$prefix/watchgate"
Decrypt the secret seed.asc file and generate a TOTP based on the same seed, current time stamp and user account name. Also print the generated password to stdout for login purpose. Within the same time period (default one minute) these passwords are identical to what "/usr/local/bin/watchgate" had generated and replaced.


.SH AUTHORS
written by Yang Li.
.SH REPORTING BUGS
github.com/netcrop/watchgate
.SH LIMITATIONS
A single user account on one machine has to be left out without using TOTP but a static password. A human needs this account for further login to other accounts in local or remote machine/VMs.
.SH LICENSE
GNU GENERAL PUBLIC LICENSE Version 2

.SH EXAMPLES
.VE
.LP

  From console prompt at Aug 03 22:33:05 node: 
  eva > watchgate adam
  LeKy3QVU
  eva > su -l adam
  Password:
  adam >

  From console prompt at Aug 03 22:34:20 node: 
  eva > watchgate adam
  IekIa3w9
  eva > su -l adam
  Password:
  adam >
